//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentistry.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCoupon
    {
        public int IdClientCoupon { get; set; }
        public string ComplaintClientCoupon { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> DateOfTheApplication { get; set; }
    
        public virtual User User { get; set; }
    }
}
