//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentistry.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int IdReception { get; set; }
        public Nullable<System.DateTime> DateReception { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdDoctor { get; set; }
        public Nullable<int> IdService { get; set; }
        public string DiagnosisReception { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Doctor Doctor1 { get; set; }
        public virtual Service Service { get; set; }
    }
}
