//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentistry.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IdUser { get; set; }
        public string NameUser { get; set; }
        public string LastNameUser { get; set; }
        public string PatronymicUser { get; set; }
        public Nullable<System.DateTime> DateOfBirthUser { get; set; }
        public Nullable<int> IdPosition { get; set; }
        public string LoginUser { get; set; }
        public string PasswordUser { get; set; }
        public byte[] PreviewUser { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdDoctor { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
